### Ontological analysis
library(clusterProfiler)
library(DOSE)
f <- read.table("geneUni.txt",header=F)
e <- bitr(f[,1],fromType="SYMBOL",toType="ENTREZID",OrgDb="org.Hs.eg.db")
uni <- as.character(e[,2])
f <- read.table("q.genes.txt",header=F)
e <- bitr(f[,1],fromType="SYMBOL",toType="ENTREZID",OrgDb="org.Hs.eg.db")
genes <- as.character(e[,2])
ego <- enrichGO(gene=genes,universe=uni,ont="BP",qvalueCutoff=0.05,readable=T,OrgDb="org.Hs.eg.db",minGSSize=5,maxGSSize=2000,readable=T)
dgn <- enrichDGN(genes,readable=T,minGSSize=5,maxGSSize=2000)
pdf("ontologyAnalysis.Covid.FunNorm.pdf")
par(mfrow=c(1,2))
barplot(ego,showCategory=20)
barplot(dgn,showCategory=20)
dev.off()
